# Generated by Django 5.2.7 on 2025-11-02 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_userprofile_email_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='coins',
            field=models.IntegerField(default=0),
        ),
    ]
