# Generated by Django 5.2.7 on 2025-11-02 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_event_created_at_event_date_event_organizer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='chat_link',
            field=models.CharField(blank=True, help_text='Telegram, WhatsApp, or phone', max_length=255),
        ),
        migrations.AlterField(
            model_name='event',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
