# Generated by Django 5.2.7 on 2025-11-05 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_event_chat_link_alter_event_latitude_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Interests',
        ),
        migrations.DeleteModel(
            name='Recommendation',
        ),
    ]
